### ISSUE TITLE
data requirement

### ISSUE THREAD

**Issue by WatsonWangZh** [kracr/document-level-relation-extraction#1]
FileNotFoundError: [Errno 2] No such file or directory: '/home/DocRE-CLiP/data/DOCRED/DOCREDlink/linkpredictiondata/entities.dict'

**Comment by WatsonWangZh** [comment]
Create triples of entity context using entity_context.py (give entity file here)

Create triples of context path using context_path.py (provide both entities to calculate path)

where is these two files?

**Comment by MonikaJain19** [comment]
updated files

**Comment by WatsonWangZh** [comment]
Thanks for your early reply. But there is still an issue:

1.Traceback (most recent call last): File "train.py", line 252, in train(opt) File "train.py", line 149, in train output = model(words=d['context_idxs'], File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/hy-tmp/document-level-relation-extraction/DocRE-CLiP/code/models/DRN.py", line 401, in forward if(params["modeltype"]=="test"): KeyError: 'modeltype'

2. Could you provide the /DOCREDlink/linkpredictiondata dataset? How to split the dataset?

**Comment by WatsonWangZh** [comment]
> updated files

Thanks for your early reply. But there is still an issue:

1.Traceback (most recent call last): File "train.py", line 252, in train(opt) File "train.py", line 149, in train output = model(words=d['context_idxs'], File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/hy-tmp/document-level-relation-extraction/DocRE-CLiP/code/models/DRN.py", line 401, in forward if(params["modeltype"]=="test"): KeyError: 'modeltype'

Could you provide the /DOCREDlink/linkpredictiondata dataset? How to split the dataset?
